### ISSUE TITLE
Add  Fe2CO3-Iron(II) carbonate in crystals/carbonates folder

### ISSUE THREAD

**Issue by prabhxjottsingh** [OpenChemistry/crystals#1]
Hey, I want to contribute in this project and want to add, **Fe2CO3 cystals** `.cif` file in the crystals folder, in carbonates topic, as I didn;t find this molecule and it is an **important iron ore** , so I believe it must be there :)

**Comment by ghutchis** [comment]
We generally get the CIF files from the Crystallographic Open Database: http://crystallography.net/cod/

I do see siderite, FeCo3 http://crystallography.net/cod/5000036.html

If you can point me to appropriate COD entries, I'd be happy to add the files. (The COD includes all minerals in the American Mineralogist database, so even uncommon ores and minerals are included.)

**Comment by prabhxjottsingh** [comment]
Oh I am really sorry, I mistyped **FeCO3** as ~~Fe2CO3~~.

I was actually talking about Siderite (FeCO3) only, and thanks for telling me the source.

Can you assign this to me ?? I would love to contribute my part in the project. :)

**Comment by prabhxjottsingh** [comment]
Hey, @ghutchis , sorry but just wanted to ask if its okay for me to ask you to label it as hacktoberfest-accepted  ??
If its not then also its fine, but just wanted to know. 
Thanks in advance for your response. :)

**Comment by ghutchis** [comment]
I don't think that's needed, since it's merged. Although I do think I'd need to mark the project as part of hacktoberfest.

**Comment by prabhxjottsingh** [comment]
Oh okay Got it, thanks. :)
