### ISSUE TITLE
Tungsten .cif issue

### ISSUE THREAD

**Issue by asamarco** [OpenChemistry/crystals#5]
Elements/W-Tungsten .cif file presents a rather obscure phase instead of a simple BCC.

i suggest as a replacement COD card 9012433.

thanks for maintaing this resource.

**Comment by ghutchis** [comment]
Thanks - fixed by [73a5bbc](https://github.com/OpenChemistry/crystals/commit/73a5bbc1007f502b163a47a98f606004ff7c4b76)

Any other common crystal structures you think it should include?

**Comment by asamarco** [comment]
Thanks, at the moment I have no further suggestions, but as I use this collection more and more often for diffraction I will keep double checking present elements. If you find it valuable i might select the most relevant compounds (mainly from the fields of microelectronics and functional thin films) that I stumble into.

**Comment by ghutchis** [comment]
Yes, that would be great. I've tried to include a good selection, but I definitely appreciate suggestions.
