### ISSUE TITLE
Zirconium .cif

### ISSUE THREAD

**Issue by asamarco** [OpenChemistry/crystals#9]
The elements/Zr.cif entry is a BCC phase of Zirconium. Zirconium has a hexagonal close-packed (hcp) crystal structure at room temperature, and it undergoes allotropic transformation to a body-centered cubic (bcc) structure at about 870°C.
I would propose to replace with the hcp or to keep both. An entry in the COD for hcp Zr is 9008523 https://www.crystallography.net/cod/9008523.html

**Comment by ghutchis** [comment]
Fixed in `HEAD`
